AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: aws nested stack example - full resource sam template

# Example of a working full resource sam template
Resources:
  DynamoDbTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    Properties:
      TableName: nested-stack-example
      AttributeDefinitions:
        - AttributeName: row_id
          AttributeType: S
      KeySchema:
        - AttributeName: row_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      FunctionName: AWS-Nested-Stack-Lambda-ProtoType
      Runtime: dotnet6
      MemorySize: 128
      Timeout: 30
      CodeUri: 
      Handler: AWS.Nested.Stacks::AWS.Nested.Stacks.Function::FunctionHandlerAsync
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDbTable
      
Outputs:
  LambdaFunctionArn:
    Description: Lambda Arn
    Value: !GetAtt LambdaFunction.Arn